name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Setup known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
    - name: Create deploy directory
      run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p ${{ secrets.DEPLOY_PATH }}"
      
    - name: Deploy to EC2 (single line command)
      run: rsync -avz --delete --exclude '.git/' --exclude '.github/' --exclude '.gitignore' ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_PATH }}
        
    - name: Set correct permissions
      if: success()
      run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "chmod -R 755 ${{ secrets.DEPLOY_PATH }}"