name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 43.205.23.225
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/var/www/html/login-app"
        strip_components: 0
        
    - name: Configure permissions
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 43.205.23.225
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          chmod -R 755 /var/www/html/login-app
          echo "Deployment completed successfully"